# Generated by Django 5.2 on 2025-04-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linked_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="optional_scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="app_optional_scopes",
                through="linked_services.AppOptionalScope",
                through_fields=("app", "scope"),
                to="linked_services.scope",
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="required_scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="app_required_scopes",
                through="linked_services.AppRequiredScope",
                through_fields=("app", "scope"),
                to="linked_services.scope",
            ),
        ),
    ]
